# Generated by Django 4.1.3 on 2022-11-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_user_isteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Lehrer'), (3, 'Schüler')], null=True),
        ),
    ]
