# Generated by Django 4.1.3 on 2022-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Lehrer'), (3, 'Schüler')], default=3),
        ),
    ]
