# Generated by Django 4.1.3 on 2022-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_user_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='target_group',
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, '7. Jahrgang'), (2, '8. Jahrgang'), (3, '9. Jahrgang'), (4, '10. Jahrgang')], default=1),
            preserve_default=False,
        ),
    ]
