# Generated by Django 4.1.3 on 2022-11-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_project_target_group_project_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
    ]
