# Generated by Django 4.1.3 on 2022-11-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_project_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='other',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
