# Generated by Django 4.1.4 on 2022-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_project_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, '5./6. Jahrgang'), (2, '7. Jahrgang'), (3, '8. Jahrgang'), (4, '9. Jahrgang'), (5, '10. Jahrgang'), (6, '11. Jahrgang'), (7, '12. Jahrgang')]),
        ),
    ]
