# Generated by Django 4.1.4 on 2022-12-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=8000)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, '5./6. Jahrgang'), (2, '7. Jahrgang'), (3, '8. Jahrgang'), (4, '9. Jahrgang'), (5, '10. Jahrgang'), (6, '11. Jahrgang'), (7, '12. Jahrgang')])),
                ('attendance', models.IntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('other', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
