# Generated by Django 4.1.4 on 2022-12-14 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_project'),
    ]

    operations = [

    ]
