# Generated by Django 4.1.4 on 2022-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_project_dazs_projectuserconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='students',
            field=models.IntegerField(default=12),
        ),
    ]
