# Generated by Django 4.1.4 on 2022-12-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_user_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dazs',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Für Sprachlerner geeignet'), (2, 'Nur für fortgeschrittene Sprachlerner geeignet'), (3, 'Nicht für Sprachlerner geeignet')], default=1),
        ),
        migrations.CreateModel(
            name='ProjectUserConnection',
            fields=[
                ('project_user_connection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
