# Generated by Django 4.1.4 on 2022-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_projectuserconnection_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('year', models.PositiveBigIntegerField(choices=[(1, '5./6. Jahrgang'), (2, '7. Jahrgang'), (3, '8. Jahrgang'), (4, '9. Jahrgang'), (5, '10. Jahrgang'), (6, '11. Jahrgang'), (7, '12. Jahrgang')], primary_key=True, serialize=False)),
                ('students', models.IntegerField()),
            ],
        ),
    ]
