# Generated by Django 4.1.4 on 2022-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, '5./6. Jahrgang'), (2, '7. Jahrgang'), (3, '8. Jahrgang'), (4, '9. Jahrgang'), (6, '11. Jahrgang'), (7, '12. Jahrgang')]),
        ),
        migrations.AlterField(
            model_name='years',
            name='year',
            field=models.PositiveBigIntegerField(choices=[(1, '5./6. Jahrgang'), (2, '7. Jahrgang'), (3, '8. Jahrgang'), (4, '9. Jahrgang'), (6, '11. Jahrgang'), (7, '12. Jahrgang')], primary_key=True, serialize=False),
        ),
    ]
