# Generated by Django 4.1.4 on 2022-12-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_projectuserconnection'),
        ('manager', '0009_alter_project_role_alter_years_year'),
    ]

    operations = [
    ]
