# Generated by Django 4.1.4 on 2022-12-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_merge_20221222_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuserconnection',
            name='partner',
        ),
        migrations.AddField(
            model_name='projectuserconnection',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectuserconnection',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectuserconnection',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Erstwunsch'), (2, 'Zweitwunsch'), (3, 'Drittwunsch')], null=True),
        ),
    ]
