# Generated by Django 4.1.4 on 2022-12-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_remove_projectuserconnection_partner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Years',
            new_name='Year',
        ),
    ]
