# Generated by Django 4.1.4 on 2022-12-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_rename_years_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
    ]
