# Generated by Django 4.1.4 on 2023-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_remove_project_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='projects',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
