# Generated by Django 4.1.4 on 2023-01-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_year_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.year'),
            preserve_default=False,
        ),
    ]
