# Generated by Django 4.1.4 on 2023-03-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.PositiveBigIntegerField(blank=True, choices=[(1, '5./6. Jahrgang'), (2, '7. Jahrgang'), (3, '8. Jahrgang'), (4, '9. Jahrgang'), (5, '10. Jahrgang'), (6, '11. Jahrgang'), (7, '12. Jahrgang')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.ForeignKey(default={'projects': 3, 'students': 60, 'year': 1}, on_delete=django.db.models.deletion.CASCADE, to='manager.year'),
        ),
    ]
