# Generated by Django 4.1.4 on 2023-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_user_year_alter_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dasz',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sprachlerner'), (2, 'Fortgeschrittener Sprachlerner'), (3, 'Kein Sprachlerner')], default=3),
        ),
    ]
