# Generated by Django 4.1.4 on 2023-03-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_user_dasz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dasz',
            new_name='dazs',
        ),
    ]
